import { Providers } from '@fsd-ddd/web/app/providers';
import './global.css';

export const metadata = {
  title: 'Welcome to fsd-ddd',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
